FROM       ubuntu:14.04
MAINTAINER goodgoblin

RUN apt-get update -y
RUN apt-get install -y \
    git                    \
    curl                   \
    build-essential        \
    autoconf               \
    man                    \
    libreadline-dev        \
    libssl-dev             \
    libxml2-dev            \
    libxslt-dev            \
    zlib1g-dev             \
    libbz2-dev
